name: pypots
channels:
    - pytorch
    - conda-forge
    - defaults
dependencies:
    - python=3.7.13
    - pip
    - numpy
    - scipy
    - scikit-learn
    - matplotlib
    - pytorch>=1.10
    - tensorboard
    - pandas
    - pip:
        - torch_sparse==0.6.13
        - torch_scatter
        - torch_geometric
        - pycorruptor
        - tsdb
