name: pypots
channels:
    - pytorch
    - conda-forge
    - nodefaults
dependencies:
    - conda-forge::python
    - conda-forge::numpy >=1.23.3  # numpy should , otherwise may encounter "number not available" when torch>1.11
    - conda-forge::scipy
    - conda-forge::pandas <2.0.0
    - conda-forge::scikit-learn
    - conda-forge::tensorboard
    - conda-forge::pip
    - conda-forge::pycorruptor
    - conda-forge::tsdb
    - conda-forge::h5py
    - pytorch::pytorch >=1.10.0