name: pypots-dev
channels:
    - conda-forge
    - pytorch
    - pyg
    - nodefaults
dependencies:
    - conda-forge::python
    - conda-forge::pip
    - conda-forge::scipy
    - conda-forge::numpy >=1.23.3  # numpy should , otherwise may encounter "number not available" when torch>1.11
    - conda-forge::scikit-learn >=0.24.1
    - conda-forge::pandas <2.0.0
    - conda-forge::h5py
    - conda-forge::tensorboard
    - conda-forge::pytest-cov
    - conda-forge::pytest-xdist
    - conda-forge::coverage
    - conda-forge::pycorruptor
    - conda-forge::tsdb
    - conda-forge::black
    - conda-forge::flake8
    - pytorch::pytorch >=1.10.0
    - pyg::pyg
    - pyg::pytorch-scatter
    - pyg::pytorch-sparse