name: pypots
channels:
    - pytorch
    - pyg
    - conda-forge
    - defaults
dependencies:
    - python=3.7.13
    - pip
    - numpy
    - scipy
    - pandas
    - scikit-learn
    - matplotlib
    - tensorboard
    - pytorch>=1.10
    - pyg
    - pip:
        - torchdiffeq
        - pycorruptor
        - tsdb
