name: PyPOTS Testing

on:
    push:
        branches:
            - main
            - dev
    pull_request:
        branches:
            - main
            - dev

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest, macOS-latest]
                python-version: [3.7, 3.9]

        steps:
            - uses: actions/checkout@v3

            - name: Set up Conda
              uses: conda-incubator/setup-miniconda@v2
              with:
                  activate-environment: pypots-test
                  python-version: ${{ matrix.python-version }}
                  environment-file: pypots/tests/environment_test.yml
                  auto-activate-base: false

            - name: Check the test environment
              run: |
                  conda activate pypots-test
                  which python
                  conda info
                  conda list

            - name: Test with pytest
              run: |
                  python -m coverage run --source=pypots -m pytest -s -n auto

            - name: Generate the LCOV report
              run: |
                  python -m coverage lcov

            - name: Submit the report
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  path-to-lcov: 'coverage.lcov'