name: PyPOTS Testing

on:
    push:
        branches:
            - main
            - dev
    pull_request:
        branches:
            - main
            - dev

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest, macOS-latest]
                python-version: [3.7, 3.9]

        steps:
            - uses: actions/checkout@v3

            - name: Set up Conda
              uses: conda-incubator/setup-miniconda@v2
              with:
                  python-version: ${{ matrix.python-version }}
                  environment-file: environment.yml
                  activate-environment: pypots

            - name: Install testing dependencies
              run: |
                  conda install pytest
                  conda install coverage

            - name: Test with pytest
              run: |
                  coverage run --source=pypots -m pytest

            - name: Generate the LCOV report
              run: |
                  coverage lcov

            - name: Submit report
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  path-to-lcov: 'coverage.lcov'